//
// Created by james on 06/01/26.
//

#ifndef FRAMEINFOINTERNAL_H
#define FRAMEINFOINTERNAL_H

#define DW_AUG_STARTER_EH_STR "eh"
#define DW_AUG_STARTER_CHR 'z'
#define DW_AUG_OPTION_LSDA_CHR 'L'
#define DW_AUG_OPTION_PERSONAILTY_ROUTINE_CHR 'P'
#define DW_AUG_OPTION_ADDRESS_POINTER_CHR 'R'


#endif //FRAMEINFOINTERNAL_H
